### ISSUE TITLE
Error with the table dependency

### ISSUE THREAD

**Issue by TathagataRoy1278** [iamdsc/smart-sanskrit-annotator#5]
After cloning the repo and downloading the required packages, I ran 

`python manage.py migrate`

Proceeding which the error was : 

> Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/home/tatan/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/tatan/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/tatan/.local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/tatan/.local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/tatan/.local/lib/python3.8/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/tatan/.local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/home/tatan/.local/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = checks.run_checks(
  File "/home/tatan/.local/lib/python3.8/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/tatan/.local/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/tatan/.local/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/tatan/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/home/tatan/.local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/tatan/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/tatan/.local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/tatan/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/tatan/Desktop/Tests/ExternalProjects/smart-sanskrit-annotator/mysite/mysite/urls.py", line 21, in <module>
    path('', include('annotatorapp.urls')),
  File "/home/tatan/.local/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/tatan/Desktop/Tests/ExternalProjects/smart-sanskrit-annotator/mysite/annotatorapp/urls.py", line 2, in <module>
    from . import views
  File "/home/tatan/Desktop/Tests/ExternalProjects/smart-sanskrit-annotator/mysite/annotatorapp/views.py", line 4, in <module>
    from .tables import WordOptionsTable, SentencesTable, WordsinsentenceTable
  File "/home/tatan/Desktop/Tests/ExternalProjects/smart-sanskrit-annotator/mysite/annotatorapp/tables.py", line 3, in <module>
    from table.columns import Column
ModuleNotFoundError: No module named 'table.columns'; 'table' is not a package

Ive searched and i didnt find any table.columns

**Comment by anandrajB** [comment]
make sure that you have  activated  your virtual environment 
if not create a virtual env using **python -m venv env**   and  **source env/scripts/activate** -- windows ,  **source env/bin/activate** --linux 

in your project settings.py    check -->  SECRET_KEY = 'xyz'

because the cloned project has the secret_key values in a seperate env file ..
I got this same issue in windows , but it works in linux .
try using linux , :)

**Comment by agrawalanshul053** [comment]
What is that secret key? Where can we find it? Where do we have to put that secret key?
