### ISSUE TITLE
ModuleNotFoundError: No module named 'romtoslp'

### ISSUE THREAD

**Issue by agrawalanshul053** [iamdsc/smart-sanskrit-annotator#6]
(venv) C:\smart-sanskrit-annotator\mysite>python manage.py scrap3
Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "E:\venv\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "E:\venv\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "E:\venv\lib\site-packages\django\core\management\__init__.py", line 257, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "E:\venv\lib\site-packages\django\core\management\__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\smart-sanskrit-annotator\mysite\annotatorapp\management\commands\scrap3.py", line 3, in <module>
    import romtoslp as conv
ModuleNotFoundError: No module named 'romtoslp'

When I tried to run the command "python manage.py scrap3" ,  this error is coming.

**Comment by krishnamrith12** [comment]
The file is available here : https://github.com/iamdsc/smart-sanskrit-annotator/tree/master/mysite/annotatorapp/management/commands

Please check the path from which you run the server

**Comment by agrawalanshul053** [comment]
I was running command "python manage.py scrap3".  So I was here: https://github.com/iamdsc/smart-sanskrit-annotator/tree/master/mysite .

**Comment by agrawalanshul053** [comment]
I ran scrap3.py in https://github.com/iamdsc/smart-sanskrit-annotator/tree/master/mysite/annotatorapp/management/commands. Thank you for your help.
